name: Python application test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        pytest

    - name: Configure Git
      run: |
        git config --global user.name "alikatteRajakala"
        git config --global user.email "alikatterajakala.com"

    - name: Add remote repository and push changes
      env:
        PAT: ${{ secrets.CLASSIC_PAT }}  # Ensure the PAT is stored as a GitHub secret
      run: |
        git remote add team1 https://alikatterajakala:${{ secrets.CLASSIC_PAT }}@github.com/Alikatte123/github-actions-python-example-forked.git
        git remote -v  # Verify remotes
        git push team1 main || echo "Push failed, check permissions or PAT scopes."
